(function(){'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),cash=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(n);
let products=window.REPROFEM_CATALOG.products.map(p=>({...p})),view='inicio',query='';
const clients=[{id:'CL-0184',name:'María Ejemplo',email:'maria@example.com',age:38,last:'07 sep 2026',orders:3,total:2185,status:'Activa'},{id:'CL-0183',name:'Sofía Muestra',email:'sofia@example.com',age:31,last:'06 sep 2026',orders:1,total:934,status:'Nueva'},{id:'CL-0182',name:'Ana Demostración',email:'ana@example.com',age:45,last:'05 sep 2026',orders:5,total:4270,status:'Activa'},{id:'CL-0181',name:'Carlos Ejemplo',email:'carlos@example.com',age:52,last:'04 sep 2026',orders:2,total:1390,status:'Seguimiento'},{id:'CL-0180',name:'Elena Prueba',email:'elena@example.com',age:29,last:'02 sep 2026',orders:1,total:1723,status:'Nueva'}];
const orders=[{id:'DEMO-0907-184',client:'María Ejemplo',items:'Biometría Hemática + HbA1c',date:'07 sep 2026',total:425,status:'Preparada'},{id:'DEMO-0906-183',client:'Sofía Muestra',items:'Hormona Antimulleriana',date:'06 sep 2026',total:1723,status:'Pendiente'},{id:'DEMO-0905-182',client:'Ana Demostración',items:'Química sanguínea 24 elementos',date:'05 sep 2026',total:934,status:'Completada'},{id:'DEMO-0904-181',client:'Carlos Ejemplo',items:'Antígeno Prostático Total',date:'04 sep 2026',total:434,status:'Preparada'},{id:'DEMO-0902-180',client:'Elena Prueba',items:'Perfil TORCH IgG e IgM',date:'02 sep 2026',total:1831,status:'Cancelada'}];
const matches=v=>!query||Object.values(v).join(' ').toLowerCase().includes(query.toLowerCase()),status=s=>`<span class="status ${s==='Pendiente'?'pending':s==='Cancelada'?'cancel':''}">${esc(s)}</span>`;
function setTitle(kicker,title){$('view-eyebrow').textContent=kicker;$('view-title').textContent=title}
function stats(){return `<div class="stats"><article class="stat"><span>ESTUDIOS ACTIVOS</span><strong>${products.length}</strong></article><article class="stat"><span>CLIENTES DEMO</span><strong>${clients.length}</strong></article><article class="stat"><span>ÓRDENES DEMO</span><strong>${orders.length}</strong></article><article class="stat"><span>VENTA SIMULADA</span><strong>${cash(orders.reduce((s,o)=>s+o.total,0))}</strong></article></div>`}
function home(){setTitle('CENTRO DE CONTROL','Buenos días.');$('admin-content').innerHTML=stats()+`<div class="panel-grid"><section class="panel"><div class="panel-head"><div><h2>Órdenes recientes</h2><p>Actividad ficticia para revisar la experiencia.</p></div><button data-view="ordenes">Ver todas</button></div>${ordersTable(orders.slice(0,4))}</section><section class="panel"><div class="panel-head"><div><h2>Actividad</h2><p>Últimos movimientos simulados.</p></div></div><div class="activity"><article><strong>Nueva orden preparada</strong><p>María Ejemplo · 2 estudios</p><time>Hace 12 minutos</time></article><article><strong>Nuevo cliente</strong><p>Sofía Muestra se agregó al CRM demo</p><time>Ayer</time></article><article><strong>Catálogo actualizado</strong><p>46 estudios disponibles</p><time>Hace 3 días</time></article></div></section></div>`}
function productRows(list){return `<table class="rows"><thead><tr><th>Estudio</th><th>Categoría</th><th>Preparación</th><th>Precio</th><th></th></tr></thead><tbody>${list.map(p=>`<tr><td class="catalog-name"><strong>${esc(p.name)}</strong><small>CÓD. ${esc(p.code)}</small></td><td>${esc(p.category)}</td><td>${esc(p.preparation||'Por confirmar')}</td><td>${cash(p.price)}</td><td><button class="danger" data-remove-product="${esc(p.id)}">Quitar</button></td></tr>`).join('')}</tbody></table>`}
function catalog(){setTitle('GESTIÓN DE PRODUCTOS','Catálogo.');const list=products.filter(matches);$('admin-content').innerHTML=`<div class="toolbar"><h2>${list.length} estudios</h2><div><input class="local-search" type="search" value="${esc(query)}" placeholder="Buscar estudio"><button class="primary" data-add-product>Agregar estudio ＋</button></div></div><section class="panel">${list.length?productRows(list):'<div class="empty">No hay estudios que coincidan.</div>'}</section>`;bindLocalSearch()}
function clientRows(list){return `<table class="rows"><thead><tr><th>Cliente</th><th>Última actividad</th><th>Órdenes</th><th>Total demo</th><th></th></tr></thead><tbody>${list.map(c=>`<tr><td class="catalog-name"><strong>${esc(c.name)}</strong><small>${esc(c.email)}</small></td><td>${esc(c.last)}</td><td>${c.orders}</td><td>${cash(c.total)}</td><td><button data-client="${c.id}">Ver ficha</button></td></tr>`).join('')}</tbody></table>`}
function crm(){setTitle('CRM DE DEMOSTRACIÓN','Clientes.');const list=clients.filter(matches);$('admin-content').innerHTML=`<div class="toolbar"><h2>${list.length} clientes ficticios</h2><div><input class="local-search" type="search" value="${esc(query)}" placeholder="Buscar cliente"></div></div><section class="panel">${clientRows(list)}</section>`;bindLocalSearch()}
function ordersTable(list){return `<table class="rows"><thead><tr><th>Orden</th><th>Cliente</th><th>Estudios</th><th>Total</th><th>Estado</th></tr></thead><tbody>${list.map(o=>`<tr><td><button data-order="${o.id}">${esc(o.id)}</button><br><small>${esc(o.date)}</small></td><td>${esc(o.client)}</td><td>${esc(o.items)}</td><td>${cash(o.total)}</td><td>${status(o.status)}</td></tr>`).join('')}</tbody></table>`}
function orderView(){setTitle('SEGUIMIENTO DE DEMOSTRACIÓN','Órdenes.');const list=orders.filter(matches);$('admin-content').innerHTML=`<div class="toolbar"><h2>${list.length} órdenes ficticias</h2><div><input class="local-search" type="search" value="${esc(query)}" placeholder="Buscar orden"></div></div><section class="panel">${ordersTable(list)}</section>`;bindLocalSearch()}
function render(){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='catalogo')catalog();else if(view==='clientes')crm();else if(view==='ordenes')orderView();else home();$('admin-content').focus({preventScroll:true})}
function bindLocalSearch(){document.querySelector('.local-search')?.addEventListener('input',e=>{query=e.target.value;render()})}
function openDetail(title,rows){$('detail-body').innerHTML=`<p class="kicker">FICHA · DEMO</p><h2 id="detail-title">${esc(title)}</h2><div class="detail-list">${rows.map(([k,v])=>`<div><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join('')}</div>`;$('detail-dialog').showModal()}
let toastTimer;function toast(t){$('admin-toast').textContent=t;$('admin-toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('admin-toast').classList.remove('show'),2200)}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view){view=b.dataset.view;query='';document.querySelector('.side').classList.remove('open');render()}if(b.hasAttribute('data-add-product'))$('product-dialog').showModal();if(b.dataset.removeProduct){products=products.filter(p=>p.id!==b.dataset.removeProduct);toast('Estudio retirado de esta sesión.');render()}if(b.dataset.client){const c=clients.find(x=>x.id===b.dataset.client);openDetail(c.name,[['ID demo',c.id],['Correo ficticio',c.email],['Edad',c.age+' años'],['Estado',c.status],['Órdenes',String(c.orders)],['Total simulado',cash(c.total)]])}if(b.dataset.order){const o=orders.find(x=>x.id===b.dataset.order);openDetail(o.id,[['Cliente',o.client],['Estudios',o.items],['Fecha',o.date],['Total',cash(o.total)],['Estado',o.status]])}if(b.hasAttribute('data-close'))b.closest('dialog').close()});
$('product-form').addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));if(products.some(p=>p.code===d.code)){toast('Ese código ya existe.');return}products.unshift({id:'demo-'+Date.now(),name:d.name,code:d.code,price:Number(d.price),category:d.category,preparation:d.preparation||null,turnaround:null,verified:true,type:'estudio'});e.currentTarget.reset();$('product-dialog').close();toast('Estudio agregado a esta sesión.');view='catalogo';render()});
$('global-search').addEventListener('input',e=>{query=e.target.value;render()});$('side-toggle').addEventListener('click',()=>document.querySelector('.side').classList.toggle('open'));render();
})();
