'use strict';
(() => {
const $=id=>document.getElementById(id), C=window.ReprofemCommerce;
const catalog=window.REPROFEM_CATALOG,products=Array.isArray(catalog?.products)?catalog.products:[];
const assistant=window.ReprofemAssistant.create(products,{normalize:C.normalize});
const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const cash=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:2}).format(n);
const price=p=>p.verified&&Number.isFinite(p.price)?cash(p.price)+' MXN':'Precio por confirmar';
const state={type:'estudio',category:'Todos',query:'',limit:8,cart:[],answers:{},step:'who',done:false};
const selected=()=>state.cart.map(id=>products.find(p=>p.id===id)).filter(Boolean);
let toastTimer,returnFocus;
const photos=['clinico-pruebas.webp','ciclo-flor.webp','fertilidad-app.webp','clinico-ultrasonido.webp'];
function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3300)}
function openDialog(id){const existing=document.querySelector('dialog[open]');if(!existing)returnFocus=document.activeElement;else existing.close();$(id).showModal()}
function closeDialog(dialog){dialog.close();if(returnFocus?.isConnected)returnFocus.focus()}
for(const dialog of document.querySelectorAll('dialog')){dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog(dialog)}});dialog.addEventListener('cancel',()=>{if(returnFocus?.isConnected)queueMicrotask(()=>returnFocus.focus())})}
$('year').textContent=new Date().getFullYear();
const header=$('header');const onScroll=()=>header.classList.toggle('scrolled',window.scrollY>80);window.addEventListener('scroll',onScroll,{passive:true});onScroll();
const menu=document.querySelector('.menu-toggle');function closeMenu(){menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Abrir menú');$('navigation').classList.remove('open')}
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Cerrar menú':'Abrir menú');$('navigation').classList.toggle('open',open)});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});
for(const a of $('navigation').querySelectorAll('a'))a.addEventListener('click',closeMenu);
const video=$('hero-video'),videoButton=$('video-toggle'),motion=matchMedia('(prefers-reduced-motion: reduce)');
function syncVideo(){videoButton.textContent=video.paused?'Reproducir video ▷':'Pausar video Ⅱ';videoButton.setAttribute('aria-label',video.paused?'Reproducir video de fondo':'Pausar video de fondo')}
videoButton.addEventListener('click',()=>{if(video.paused)video.play().catch(()=>toast('El video no está disponible. Puedes seguir explorando la página.'));else video.pause()});video.addEventListener('play',syncVideo);video.addEventListener('pause',syncVideo);if(!motion.matches)video.play().catch(syncVideo);motion.addEventListener('change',e=>{if(e.matches)video.pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden)video.pause()});
function renderCatalogShell(){
const categories=['Todos',...new Set(products.filter(p=>p.type==='estudio').map(p=>p.category))];
$('catalog-content').innerHTML=`<div class="catalog-toolbar"><div class="type-switch" role="group" aria-label="Tipo de servicio">${products.some(p=>p.type==='paquete')?'<button data-type="paquete" aria-pressed="false">Paquetes</button>':''}<button data-type="estudio" aria-pressed="true">Estudios de laboratorio</button></div><label class="search-box"><span aria-hidden="true">⌕</span><input id="catalog-search" type="search" placeholder="Busca por nombre o código" aria-label="Buscar estudios por nombre o código" autocomplete="off"></label></div><div class="category-menu-head"><span>MENÚ DE ESTUDIOS</span><strong>Explora por categoría</strong><small>Elige una opción para filtrar el catálogo</small></div><div id="categories" class="categories" role="group" aria-label="Menú de categorías de estudios">${categories.map(c=>{const count=c==='Todos'?products.length:products.filter(p=>p.category===c).length;return `<button data-filter="${esc(c)}" aria-pressed="${c==='Todos'}"><span>${esc(c)}</span><small>${count} ${count===1?'estudio':'estudios'}</small><b aria-hidden="true">↗</b></button>`}).join('')}</div><div class="results-meta"><span id="results-count" role="status" aria-live="polite"></span><span>Una selección por persona</span></div><div id="results"></div><div id="catalog-more"></div><div class="catalog-help"><p>¿Tienes una orden médica?<br><span>Busca tus estudios por nombre. La selección final debe seguir la indicación de tu profesional.</span></p><button class="text-button" data-action="cart">Ver mi selección ↗</button></div>`;
$('catalog-search').addEventListener('input',e=>{state.query=e.target.value;state.limit=8;if(state.query){state.type='all';state.category='Todos'}renderResults()});renderResults();
}
function renderResults(){
for(const b of document.querySelectorAll('[data-type]'))b.setAttribute('aria-pressed',String(b.dataset.type===state.type));for(const b of document.querySelectorAll('[data-filter]'))b.setAttribute('aria-pressed',String(b.dataset.filter===state.category));$('categories').hidden=state.type==='paquete';
const matches=C.filter(products,state.query,state.category,state.type),visible=matches.slice(0,state.limit);$('results-count').textContent=`${matches.length} opciones${catalog.status==='pending-source'?' en vista previa':''}`;$('results').className=state.type==='paquete'?'package-grid':'study-list';
$('results').innerHTML=visible.length?visible.map((p,i)=>{const added=state.cart.includes(p.id);const add=`<button class="round-add ${added?'added':''}" data-add="${esc(p.id)}" aria-label="${added?'Ya agregado':'Agregar'} ${esc(p.name)}" aria-pressed="${added}">${added?'✓':'+'}</button>`;return state.type==='paquete'?`<article class="package"><button class="package-image" data-detail="${esc(p.id)}" aria-label="Ver ${esc(p.name)}"><img src="assets/img/${photos[i%photos.length]}" alt="" loading="lazy"><span>0${i+1} / PAQUETE</span></button><div class="package-title"><h3><button data-detail="${esc(p.id)}">${esc(p.name)}</button></h3>${add}</div><p>${p.includes.length} conceptos · Contenido por validar</p><div class="package-price">${esc(price(p))}</div><button class="text-button" data-detail="${esc(p.id)}">Ver qué incluye ↗</button></article>`:`<article class="study-row"><span class="study-number">${String(i+1).padStart(2,'0')}</span><div><span class="study-category">${esc(p.category)} · CÓD. ${esc(p.code||p.id)}</span><h3><button data-detail="${esc(p.id)}">${esc(p.name)}</button></h3></div><span class="study-price">${esc(price(p))}</span><button class="text-button study-details" data-detail="${esc(p.id)}">Detalles ↗</button>${add}</article>`}).join(''):`<div class="empty-state"><p class="eyebrow">PODEMOS EMPEZAR DE NUEVO</p><h3>No encontramos esa búsqueda.</h3><p>Prueba con otro nombre o explora el catálogo completo.</p><button class="button outline" data-action="clear-search">Ver todas las opciones ↗</button></div>`;
$('catalog-more').innerHTML=matches.length>visible.length?`<button class="button outline" data-action="more">Mostrar más estudios ↓</button>`:'';
}
function syncCart(){for(const count of document.querySelectorAll('.cart-count'))count.textContent=state.cart.length;document.querySelector('.bag').setAttribute('aria-label',`Abrir selección, ${state.cart.length} productos`);const dock=$('cart-dock'),has=state.cart.length>0;dock.hidden=!has;dock.classList.toggle('visible',has);document.body.classList.toggle('has-cart',has);$('cart-dock-label').textContent=`${state.cart.length} ${state.cart.length===1?'estudio agregado':'estudios agregados'}`;$('cart-dock-total').textContent=has?subtotal():'';renderResults();if($('cart-dialog').open)renderCart()}
function add(id){if(!products.some(p=>p.id===id))return;if(state.cart.includes(id)){toast('Este estudio ya está en tu selección.');return}state.cart.push(id);state.done=false;syncCart();toast('Agregado a tu selección. Continúa cuando quieras.');if($('detail-dialog').open)showDetail(id,false)}
function remove(id){state.cart=state.cart.filter(x=>x!==id);state.done=false;syncCart();if(!state.cart.length)state.step='who'}
function showDetail(id,open=true){const p=products.find(x=>x.id===id);if(!p)return;const included=p.includes.length?`<h3 class="detail-subtitle">Contenido del paquete</h3><ul class="included-list">${p.includes.map(n=>`<li>${esc(n)}</li>`).join('')}</ul>`:'';
$('detail-content').innerHTML=`<p class="eyebrow">${esc(p.category)} · CÓD. ${esc(p.code||p.id)}</p><h2 id="detail-title">${esc(p.name)}</h2><p class="detail-price">${esc(price(p))}</p>${included}<div class="detail-facts"><div><span>Preparación</span><p>${esc(p.verified&&p.preparation?p.preparation:'Pendiente de validación por el laboratorio.')}</p></div><div><span>Tiempo de resultados</span><p>${esc(p.verified&&p.turnaround?p.turnaround:'Por confirmar.')}</p></div></div>${(p.warnings||[]).map(w=>`<p class="notice">${esc(w)}</p>`).join('')}<p class="detail-source">Precio e indicaciones del catálogo proporcionado por REPROFEM. Confirma cualquier duda con el laboratorio; no modifiques un tratamiento por tu cuenta.</p><div class="detail-actions"><button class="button primary" data-add="${esc(p.id)}" ${state.cart.includes(id)?'disabled':''}>${state.cart.includes(id)?'Agregado ✓':'Agregar a mi selección + '}</button><button class="text-button" data-action="cart">Ver selección ↗</button></div>`;if(open)openDialog('detail-dialog');
}
function subtotal(){const n=C.total(selected());return n===null?'Por confirmar':cash(n)+' MXN'}
function renderCart(){const items=selected(),overlap=C.overlaps(items);
$('cart-content').innerHTML=items.length?`<p class="cart-intro">${items.length} opciones elegidas. Puedes cambiar de idea.</p><div class="cart-items">${items.map(p=>`<article class="cart-item"><div><small>${esc(p.category)}</small><h3>${esc(p.name)}</h3><span>${esc(price(p))}</span></div><button data-remove="${esc(p.id)}" class="remove-button" aria-label="Quitar ${esc(p.name)}">Quitar</button></article>`).join('')}</div>${overlap.length?`<p class="notice"><strong>Revisa estas coincidencias:</strong> ${overlap.map(esc).join(', ')}. Aparecen en más de una opción. Confirma el contenido con el laboratorio.</p>`:''}<div class="cart-total"><span>Total estimado</span><strong>${subtotal()}</strong></div><p class="notice">Precios del catálogo proporcionado por REPROFEM. No se realizan cobros ni se reservan citas en esta vista previa.</p><button class="button primary full" data-action="guide">Continuar paso a paso ↗</button><button class="text-button full" data-action="browse">Seguir explorando</button>`:`<div class="empty-state"><span class="empty-symbol" aria-hidden="true">+</span><h3>Todo comienza con un paso.</h3><p>Agrega un estudio para preparar tu selección.</p><button class="button primary" data-action="browse">Explorar estudios ↗</button></div>`;
}
function guideSidebar(){const items=selected();$('guide-summary').innerHTML=`<p class="eyebrow">TU SELECCIÓN</p><h3 class="sidebar-title">Un paso<br>más cerca.</h3><div class="sidebar-items">${items.map(p=>`<div><strong>${esc(p.name)}</strong><span>${esc(price(p))}</span></div>`).join('')}</div><div class="sidebar-total"><span>Total estimado</span><strong>${subtotal()}</strong></div><button class="text-button" data-action="edit-cart">Editar selección ↗</button><p class="sidebar-note">Sin cargos. Sin reservas.<br>Primero, revisa cada detalle.</p>`}
const labels={who:'Para quién',name:'Nombre',age:'Edad',tutor:'Tutor',order:'Orden médica',contact:'Contacto',date:'Tu visita',review:'Revisión'};
function getQuestion(){const a=state.answers,other=a.who==='other',minor=C.age(a.age)&&Number(a.age)<18;switch(state.step){
case 'who':return {title:'Primero, ¿para quién<br>son los estudios?',hint:'Prepara una selección por persona. Vamos a acompañarte una pregunta a la vez.',options:[['self','Son para mí','Quiero preparar mis estudios.'],['other','Son para alguien más','Estoy acompañando a otra persona.']]};
case 'name':return {title:other?'¿Cómo se llama<br>la persona que atenderemos?':'Hola. ¿Cómo<br>te llamas?',hint:'Usa un nombre ficticio para recorrer esta vista previa.',type:'text',label:other?'Nombre de la persona':'Tu nombre',placeholder:'Por ejemplo, Alex Ejemplo',max:100};
case 'age':return {title:other?`¿Qué edad tiene<br>${esc((a.name||'').split(' ')[0])}?`:`Gracias, ${esc((a.name||'').split(' ')[0])}.<br>¿Qué edad tienes?`,hint:'En años cumplidos. Para menores de edad incluiremos a su madre, padre o tutor.',type:'number',label:'Edad en años cumplidos',placeholder:'Por ejemplo, 32',min:0,max:120};
case 'tutor':return {title:'¿Quién acompañará<br>a la persona menor?',hint:'El recorrido requiere el nombre de su madre, padre o tutor. Usa datos ficticios.',type:'text',label:'Nombre de madre, padre o tutor',placeholder:'Nombre del adulto responsable',max:100};
case 'order':return {title:other?'¿Cuentan con<br>una orden médica?':'¿Tienes una<br>orden médica?',hint:'Esto nos ayuda a organizar el siguiente paso. No necesitas subir archivos en esta demo.',options:[['yes','Sí, tengo una orden','La selección debe coincidir con ella.'],['no','No tengo una orden','Necesito revisar las opciones con el equipo.'],['unsure','Prefiero confirmarlo después','Puedo avanzar con mi resumen.']]};
case 'contact':return {title:'¿A qué correo<br>daríamos seguimiento?',hint:minor?'Usa un correo ficticio del adulto responsable. No enviaremos mensajes.':'Es solo una prueba del recorrido. Usa un correo ficticio; no enviaremos mensajes.',type:'email',label:minor?'Correo del adulto responsable':'Correo de contacto',placeholder:'prueba@example.com',max:150};
case 'date':return {title:'¿Qué día<br>te gustaría venir?',hint:'Indica una preferencia o déjala pendiente. No representa disponibilidad ni una cita reservada.',type:'date',label:'Fecha preferida (opcional)',min:C.today()};
default:return {title:'Tu siguiente paso,<br>en una sola vista.',hint:'Revisa tus datos y tu selección. Todavía no hay una cita ni un cobro.'};
}}
function firstInvalid(){return C.steps(state.answers).find(key=>key!=='review'&&C.validate(key,state.answers[key]))}
function startGuide(){if(!state.cart.length){renderCart();openDialog('cart-dialog');return}if(state.done){state.done=false;state.step='review'}if(state.step==='review'&&firstInvalid())state.step=firstInvalid();openDialog('guide-dialog');renderGuide()}
function renderGuide(){guideSidebar();const path=C.steps(state.answers);if(!path.includes(state.step))state.step='who';const index=path.indexOf(state.step);$('step-label').textContent=state.done?'Resumen preparado':`PASO ${index+1} DE ${path.length} · ${labels[state.step].toUpperCase()}`;$('progress').value=state.done?100:Math.round((index+1)/path.length*100);if(state.done){renderDone();return}
const q=getQuestion(),value=state.answers[state.step]??'';
let fields='';if(q.options)fields=`<fieldset class="choices"><legend class="sr-only">${esc(labels[state.step])}</legend>${q.options.map(([val,title,sub])=>`<label class="choice"><input type="radio" name="answer" value="${val}" ${value===val?'checked':''}><span><strong>${esc(title)}</strong><small>${esc(sub)}</small></span><span class="choice-circle" aria-hidden="true"></span></label>`).join('')}</fieldset>`;
else if(state.step==='review')fields=reviewHtml();
else fields=`<label class="input-label" for="guide-input">${esc(q.label)}</label><input class="guide-input" id="guide-input" name="answer" type="${q.type}" value="${esc(value)}" placeholder="${esc(q.placeholder??'')}" ${q.min!==undefined?`min="${q.min}"`:''} ${q.max!==undefined?(q.type==='number'?`max="${q.max}" step="1" inputmode="numeric"`:`maxlength="${q.max}"`):''} autocomplete="off" aria-describedby="guide-hint form-error">${state.step==='date'?'<button type="button" class="text-button date-skip" data-action="skip-date">Prefiero definirlo después</button>':''}`;
$('guide-content').innerHTML=`<form id="guide-form" novalidate><h2 id="guide-title" tabindex="-1">${q.title}</h2><p id="guide-hint" class="guide-hint">${q.hint}</p>${fields}<p id="form-error" class="form-error" role="alert"></p><div class="guide-buttons">${index>0?'<button type="button" class="back-button" data-action="back">← Atrás</button>':'<span></span>'}<button class="button primary" type="submit">${state.step==='review'?'Preparar resumen':'Continuar'} <span aria-hidden="true">↗</span></button></div></form>`;
$('guide-form').addEventListener('submit',submitGuide);$('guide-title').focus({preventScroll:true});
}
function formatDay(value){return value?new Date(value+'T12:00:00').toLocaleDateString('es-MX',{day:'numeric',month:'long',year:'numeric'}):'Por definir'}
function reviewHtml(){const a=state.answers;return `<div class="review-data">${[['name','Paciente',a.name],['age','Edad',a.age+' años'],...(Number(a.age)<18?[['tutor','Adulto responsable',a.tutor]]:[]),['order','Orden médica',a.order==='yes'?'Sí':a.order==='no'?'No':'Por confirmar'],['contact','Correo',a.contact],['date','Preferencia de visita',formatDay(a.date)]].map(([key,label,val])=>`<div><span>${label}</span><strong>${esc(val)}</strong><button type="button" data-edit="${key}" aria-label="Editar ${label}">Editar</button></div>`).join('')}</div><div class="review-products"><h3>Tu selección <button type="button" data-action="edit-cart">Editar</button></h3>${selected().map(p=>`<div><span>${esc(p.name)}</span><span>${esc(price(p))}</span></div>`).join('')}<div class="review-total"><strong>Total estimado</strong><strong>${subtotal()}</strong></div></div><p class="notice">${a.order==='no'?'Revisa tu selección con el laboratorio o tu profesional de salud. ':''}Consulta abajo las indicaciones de tus estudios. La disponibilidad debe confirmarse con el laboratorio; esta fecha es solo una preferencia.</p>${preparationHtml()}<label class="consent"><input type="checkbox" name="ack"><span>Entiendo que esto es una vista previa: el resumen no confirma una compra, una cita ni un pago.</span></label>`}
function preparationHtml(){const groups=new Map();for(const p of selected()){const text=p.preparation||'Preparación pendiente de aclaración: confirma con el laboratorio antes de acudir.';if(!groups.has(text))groups.set(text,[]);groups.get(text).push(p.name)}return '<details class="preparation-summary"><summary>Antes de tu visita <span aria-hidden="true">+</span></summary><p>Indicaciones del catálogo. No modifiques un tratamiento por tu cuenta; consulta cualquier duda con el laboratorio.</p>'+[...groups].map(([text,names])=>'<div><strong>'+names.map(esc).join(' · ')+'</strong><p>'+esc(text)+'</p></div>').join('')+selected().filter(p=>p.warnings?.length).map(p=>'<p class="notice">'+esc(p.name)+': '+p.warnings.map(esc).join(' ')+'</p>').join('')+'</details>'}
function captureAnswer(){const form=$('guide-form');return form?String(new FormData(form).get('answer')??'').trim():''}
function submitGuide(e){e.preventDefault();if(state.step==='review'){const invalid=firstInvalid();if(invalid){state.step=invalid;renderGuide();return}if(!new FormData(e.currentTarget).has('ack')){$('form-error').textContent='Confirma que entiendes el alcance de esta vista previa.';return}if(!state.cart.length){$('form-error').textContent='Agrega al menos un estudio para preparar el resumen.';return}state.done=true;renderGuide();return}
const answer=captureAnswer(),error=C.validate(state.step,answer);if(error){$('form-error').textContent=error;const input=$('guide-input');if(input){input.setAttribute('aria-invalid','true');input.focus()}return}state.answers[state.step]=answer;if(state.step==='age'&&Number(answer)>=18)delete state.answers.tutor;const path=C.steps(state.answers);state.step=path[path.indexOf(state.step)+1];renderGuide();
}
function renderDone(){$('guide-content').innerHTML=`<div class="complete-mark" aria-hidden="true">✓</div><h2 id="guide-title" tabindex="-1">Tu resumen<br>está listo.</h2><p class="guide-hint">${esc((state.answers.name||'').split(' ')[0])}, ya puedes revisar o descargar tu selección. Nada se ha enviado ni cobrado.</p><div class="completion-note"><strong>Esto aún no es una compra ni una cita.</strong><p>Para completar la contratación se requieren la confirmación del laboratorio, una agenda y una pasarela de pago conectadas.</p></div><button class="button primary full" data-action="download">Descargar mi resumen ↓</button><button class="text-button full" data-action="review-again">Volver a revisar</button><button class="text-button full" data-action="finish">Cerrar y borrar mis datos</button>`;$('guide-title').focus({preventScroll:true})}
function downloadSummary(){const a=state.answers;const lines=['REPROFEM MÉXICO — RESUMEN DE VISTA PREVIA','NO ES UNA ORDEN, RESERVA, CONFIRMACIÓN NI COMPROBANTE DE PAGO.','',`Paciente: ${a.name}`,`Edad: ${a.age} años`,...(Number(a.age)<18?[`Madre, padre o tutor: ${a.tutor}`]:[]),`Correo: ${a.contact}`,`Preferencia de fecha (no reservada): ${formatDay(a.date)}`,`Orden médica: ${a.order==='yes'?'Sí':a.order==='no'?'No':'Por confirmar'}`,'','SELECCIÓN',...selected().flatMap(p=>[`- ${p.code}: ${p.name} — ${price(p)}`,`  Preparación: ${p.preparation||'Confirmar con el laboratorio.'}`,`  Entrega: ${p.turnaround||'Confirmar con el laboratorio.'}`,...(p.warnings||[]).map(w=>'  Aviso: '+w)]),'',`Total estimado: ${subtotal()}`,'Precios e indicaciones del catálogo proporcionado por REPROFEM. Disponibilidad y dudas clínicas: confirmar con el laboratorio.','No se han enviado datos al laboratorio ni se ha realizado ningún cobro.'];const blob=new Blob(['\uFEFF'+lines.join('\n')],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),aTag=document.createElement('a');aTag.href=url;aTag.download='reprofem-resumen-vista-previa.txt';aTag.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function resetAnswers(){state.answers={};state.step='who';state.done=false;$('guide-content').replaceChildren();$('guide-summary').replaceChildren()}
let chatStarted=false,chatBusy=false;
const chatText=text=>esc(text).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\n\n/g,'<br><br>');
function chatSuggestions(items=[]){$('chat-suggestions').innerHTML=items.map(x=>`<button type="button" data-chat-question="${esc(x)}">${esc(x)}</button>`).join('')}
function chatMessage(role,text,productsFound=[]){const item=document.createElement('article');item.className=`chat-message ${role}`;item.innerHTML=`<span>${role==='assistant'?'REPROFEM':'TÚ'}</span><p>${chatText(text)}</p>${productsFound.length?`<div class="chat-products">${productsFound.map(p=>`<div><small>CÓD. ${esc(p.code)} · ${esc(p.category)}</small><strong>${esc(p.name)}</strong><span>${esc(price(p))}</span><div><button data-detail="${esc(p.id)}">Ver detalle</button><button data-add="${esc(p.id)}">Agregar +</button></div></div>`).join('')}</div>`:''}`;$('chat-messages').append(item);$('chat-messages').scrollTop=$('chat-messages').scrollHeight;return item}
function openChat(){const panel=$('chat-panel');panel.hidden=false;document.body.classList.add('chat-open');$('chat-launcher').setAttribute('aria-expanded','true');if(!chatStarted){chatStarted=true;chatMessage('assistant','Hola, soy el asistente virtual de REPROFEM. Puedo ayudarte a buscar un estudio y consultar su **precio, preparación o tiempo de entrega**. También puedo explicarte cómo armar tu selección. ¿Qué te gustaría saber?');chatSuggestions(['¿Cuánto cuesta la progesterona?','¿Qué estudios requieren ayuno?','Ver salud femenina','¿Cómo funciona el carrito?'])}setTimeout(()=>$('chat-input').focus(),80)}
function closeChat(){document.body.classList.remove('chat-open');$('chat-panel').hidden=true;$('chat-launcher').setAttribute('aria-expanded','false');$('chat-launcher').focus()}
async function askChat(question){const q=String(question||'').trim();if(!q||chatBusy)return;chatBusy=true;chatMessage('user',q);chatSuggestions([]);$('chat-input').value='';$('chat-input').disabled=true;$('chat-form').querySelector('button').disabled=true;const thinking=chatMessage('thinking','Revisando el catálogo y preparando una respuesta clara…');const answer=assistant.reply(q,{cart:selected(),total:state.cart.length?subtotal():''});const delay=Math.min(2300,Math.max(1050,700+answer.text.length*4));await new Promise(resolve=>setTimeout(resolve,delay));thinking.remove();chatMessage('assistant',answer.text,answer.products);chatSuggestions(answer.suggestions);$('chat-input').disabled=false;$('chat-form').querySelector('button').disabled=false;chatBusy=false;$('chat-input').focus()}
$('chat-launcher').addEventListener('click',openChat);$('chat-close').addEventListener('click',closeChat);$('chat-form').addEventListener('submit',e=>{e.preventDefault();askChat($('chat-input').value)});$('chat-suggestions').addEventListener('click',e=>{const b=e.target.closest('[data-chat-question]');if(b)askChat(b.dataset.chatQuestion)});
$('reset-guide').addEventListener('click',()=>{resetAnswers();renderGuide();toast('Los datos del recorrido se borraron. Tu selección sigue disponible.')});
document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;
if(b.hasAttribute('data-close')){closeDialog(b.closest('dialog'));return}if(b.dataset.add){add(b.dataset.add);return}if(b.dataset.remove){remove(b.dataset.remove);return}if(b.dataset.detail){showDetail(b.dataset.detail);return}
if(b.dataset.type){state.type=b.dataset.type;state.category='Todos';state.limit=8;renderResults();return}if(b.dataset.filter){state.category=b.dataset.filter;state.limit=8;renderResults();return}
if(b.dataset.category){state.category=b.dataset.category==='Paquetes'?'Todos':b.dataset.category;state.type=b.dataset.category==='Paquetes'&&products.some(p=>p.type==='paquete')?'paquete':'estudio';state.query='';state.limit=8;$('catalog-search').value='';renderResults();return}if(b.dataset.edit){state.step=b.dataset.edit;renderGuide();return}
switch(b.dataset.action){
case 'cart':renderCart();openDialog('cart-dialog');break;
case 'privacy':openDialog('privacy-dialog');break;
case 'guide':startGuide();break;
case 'more':state.limit+=12;renderResults();break;
case 'clear-search':state.query='';state.category='Todos';state.type='all';state.limit=8;$('catalog-search').value='';renderResults();$('catalog-search').focus();break;
case 'browse':for(const d of document.querySelectorAll('dialog[open]'))closeDialog(d);document.querySelector('#catalogo').scrollIntoView({behavior:motion.matches?'instant':'smooth'});break;
case 'edit-cart':state.done=false;state.step='review';renderCart();openDialog('cart-dialog');break;
case 'back':{if(state.step!=='review')state.answers[state.step]=captureAnswer();const path=C.steps(state.answers);state.step=path[Math.max(0,path.indexOf(state.step)-1)];renderGuide();break}
case 'skip-date':state.answers.date='';state.step='review';renderGuide();break;
case 'review-again':state.done=false;state.step='review';renderGuide();break;
case 'download':downloadSummary();break;
case 'finish':resetAnswers();closeDialog($('guide-dialog'));toast('Listo. Tus datos personales se borraron.');break;
}});
renderCatalogShell();
})();
