(function(root){
'use strict';
const STOP=new Set('a al algo como con cual cuales cuanto cuantos de del el en es esta este hay la las lo los me mi para por que quiero se si su te tu un una ver y yo'.split(' '));
const money=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:2}).format(n)+' MXN';
function create(products,{normalize}={}){
const norm=normalize||((v)=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim());
const token=v=>norm(v).split(/[^a-z0-9]+/).filter(x=>x.length>2&&!STOP.has(x));
const find=q=>{const n=norm(q),code=(q.match(/\b\d{3,6}\b/)||[])[0];if(code){const p=products.find(x=>String(x.code)===code);if(p)return p}let best=null,score=0;for(const p of products){const name=norm(p.name);let s=name.length>4&&n.includes(name)?20:0;const wanted=token(q),have=new Set(token(p.name+' '+p.category));for(const t of wanted)if(have.has(t))s+=3;else if([...have].some(h=>h.startsWith(t)||t.startsWith(h)))s+=1;if(s>score){score=s;best=p}}return score>=3?best:null};
const categories=[...new Set(products.map(p=>p.category))];
const suggestions=['¿Cuánto cuesta la progesterona?','¿Qué estudios requieren ayuno?','Ver salud femenina','¿Cómo funciona el carrito?'];
function productAnswer(p,q){const n=norm(q),parts=[`Encontré **${p.name}** (código ${p.code}).`];parts.push(/precio|cuesta|costo|vale/.test(n)?`Su precio en el catálogo es **${money(p.price)}**.`:`Precio: **${money(p.price)}**.`);if(/ayuno|prepar|antes|requisito/.test(n))parts.push(p.preparation?`Preparación indicada: **${p.preparation}**.`:'La preparación de este estudio está pendiente de aclaración. Confírmala con el laboratorio antes de acudir.');if(/resultado|entrega|tarda|tiempo/.test(n))parts.push(p.turnaround?`Tiempo de entrega indicado: **${p.turnaround}**.`:'El tiempo de entrega debe confirmarse con el laboratorio.');if(p.warnings?.length)parts.push('Hay un dato del documento original que necesita confirmación con el laboratorio.');parts.push('Puedes abrir el detalle o agregarlo a tu selección.');return{text:parts.join('\n\n'),products:[p],suggestions:[`¿Qué preparación requiere ${p.name}?`,`¿Cuánto tarda ${p.name}?`,'¿Cómo funciona el carrito?']}}
function reply(question,context={}){const q=String(question??'').trim(),n=norm(q);if(!q)return{text:'Escribe el nombre o código de un estudio y lo reviso contigo.',products:[],suggestions};
if(/dolor intenso|desmayo|dificultad para respirar|sangrado abundante|emergencia|urgencia/.test(n))return{text:'Siento que estés pasando por esto. Si hay dolor intenso, desmayo, dificultad para respirar o sangrado abundante, busca atención médica urgente o los servicios de emergencia de tu localidad. Este asistente no puede valorar una urgencia.',products:[],suggestions:['Buscar un estudio por nombre']};
if(/sintoma|que estudio necesito|cual estudio necesito|recomiend|diagnost|tengo dolor|me duele|estoy enfer/.test(n))return{text:'Entiendo que quieras una respuesta clara. No sería seguro elegir un estudio solo a partir de síntomas: eso requiere una valoración profesional. Si ya tienes una indicación u orden médica, puedo ayudarte a encontrar el estudio por nombre o código y explicarte su precio, preparación y tiempo de entrega.',products:[],suggestions:['Buscar por código','Ver categorías','Consultar preparación']};
if(/hola|buenos dias|buenas tardes|ayuda|que puedes hacer/.test(n))return{text:'Hola. Puedo ayudarte a buscar un estudio y consultar su **precio, preparación o tiempo de entrega**. También puedo explicarte el carrito y el recorrido de compra. Mis respuestas se basan en el catálogo de REPROFEM y no sustituyen una valoración médica.',products:[],suggestions};
if(/carrito|seleccion|comprar|pagar|compra/.test(n)){const count=context.cart?.length||0,total=context.total;return{text:count?`Tienes **${count} ${count===1?'estudio':'estudios'}** en tu selección${total?`, con un total estimado de **${total}**`:''}. Usa “Revisar y continuar” en la barra inferior para comprobar los datos y preparar tu resumen. En esta vista previa todavía no se realizan cobros ni se confirman citas.`:'Agrega un estudio con el botón **+**. En cuanto lo hagas aparecerá una barra fija en la parte inferior para revisar la selección y continuar. En esta vista previa todavía no se realizan cobros ni se confirman citas.',products:[],suggestions:['Buscar un estudio','Ver categorías']};}
if(/categoria|menu|ver estudios|salud femenina|fertilidad|hormona|prenatal|solicitados/.test(n)){const matched=categories.find(c=>n.includes(norm(c))),list=matched?products.filter(p=>p.category===matched):[];return{text:matched?`En **${matched}** hay ${list.length} estudios. Te muestro algunos para que puedas revisar sus detalles.`:`El catálogo está organizado en ${categories.length} categorías: **${categories.join(', ')}**. Puedes elegir una desde el menú de estudios.`,products:list.slice(0,3),suggestions:['Ver salud femenina','Ver fertilidad','Buscar por código']};}
if(/ayuno/.test(n)){const list=products.filter(p=>/ayuno/i.test(p.preparation||''));return{text:`Encontré **${list.length} estudios** cuya preparación menciona ayuno. La duración cambia según el estudio; revisa siempre el detalle y no modifiques medicamentos por tu cuenta.`,products:list.slice(0,3),suggestions:['Buscar otro estudio','Ver categorías']};}
const p=find(q);if(p)return productAnswer(p,q);
if(/cita|agenda|disponibilidad/.test(n))return{text:'La agenda todavía no está conectada en esta vista previa. Puedes preparar tu selección y descargar un resumen, pero la fecha y la disponibilidad deben confirmarse directamente con el laboratorio.',products:[],suggestions:['Buscar un estudio','¿Cómo funciona el carrito?']};
if(/privacidad|datos|guardan|inteligencia artificial/.test(n))return{text:'Esta conversación permanece únicamente en la memoria de esta página mientras la tienes abierta. No se envía al laboratorio ni a un servicio externo y desaparece al recargar. Evita escribir datos sensibles en esta vista previa.',products:[],suggestions};
return{text:'No encontré una coincidencia segura. Prueba con el **nombre completo o el código** del estudio. También puedo mostrarte las categorías o explicarte cómo usar el carrito.',products:[],suggestions:['Ver categorías','Buscar por código','¿Cómo funciona el carrito?']};}
return{reply,find};}
const api={create};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.ReprofemAssistant=api;
})(typeof window!=='undefined'?window:this);
