(function(root){
'use strict';
const STOP=new Set('a al algo como con cual cuales cuanto cuantos de del el en es esta este hay la las lo los me mi para por que quiero se si su te tu un una ver y yo estudio estudios prueba pruebas'.split(' '));
const money=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:2}).format(n)+' MXN';
function create(products,{normalize,knowledge}={}){
const norm=normalize||((v)=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()),K=knowledge||root.REPROFEM_STUDY_KNOWLEDGE||{};
const token=v=>norm(v).split(/[^a-z0-9]+/).filter(x=>x.length>2&&!STOP.has(x));
const distance=(a,b)=>{const m=Array.from({length:a.length+1},(_,i)=>[i]);for(let j=1;j<=b.length;j++)m[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)m[i][j]=Math.min(m[i-1][j]+1,m[i][j-1]+1,m[i-1][j-1]+(a[i-1]===b[j-1]?0:1));return m[a.length][b.length]};
const profile=p=>{const k=K[String(p.code)]||{};return norm([p.name,p.category,...(k.aliases||[])].join(' '))};
function ranked(q){const n=norm(q),wanted=token(q),code=(String(q).match(/\b\d{3,6}\b/)||[])[0];return products.map(p=>{if(code&&String(p.code)===code)return{p,score:100};const k=K[String(p.code)]||{},phrases=[p.name,...(k.aliases||[])].map(norm).filter(Boolean),have=new Set(token(profile(p)));let score=phrases.some(x=>x.length>3&&n.includes(x))?35:0;for(const t of wanted){if(have.has(t))score+=6;else{const near=[...have].reduce((best,h)=>Math.min(best,distance(t,h)),99);if(near<=1)score+=4;else if(near===2&&t.length>6)score+=2}}return{p,score}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score)}
const find=q=>{const list=ranked(q);return list[0]&&list[0].score>=4?list[0].p:null},categories=[...new Set(products.map(p=>p.category))];
const suggestions=['¿Para qué sirve la HbA1c?','¿Qué estudios requieren ayuno?','¿Cuánto cuesta la progesterona?','¿Cómo funciona el carrito?'];let lastProductId=null;
const getLast=()=>products.find(p=>p.id===lastProductId)||null,sourceFor=p=>{const s=K[String(p.code)]?.source;return s?[s]:[]};
function productAnswer(p,q){lastProductId=p.id;const n=norm(q),k=K[String(p.code)]||{},parts=[`Encontré **${p.name}** (código ${p.code}).`];if(/para que|sirve|utilidad|explica|informacion|que es|que mide|analiza|detecta/.test(n)||!/(precio|cuesta|costo|ayuno|prepar|entrega|tarda|tiempo)/.test(n)){if(k.purpose)parts.push(`**¿Para qué se usa?** ${k.purpose}`);if(k.measures)parts.push(`**¿Qué analiza?** ${k.measures}`)}if(/precio|cuesta|costo|vale/.test(n))parts.push(`Precio del catálogo: **${money(p.price)}**.`);if(/ayuno|prepar|antes|requisito/.test(n))parts.push(p.preparation?`Preparación indicada por REPROFEM: **${p.preparation}**.`:'La preparación del documento original es ambigua. Confírmala con REPROFEM antes de acudir.');if(/resultado|entrega|tarda|tiempo/.test(n)&&!/mi resultado|resultado (alto|bajo|positivo|negativo)|interpret/.test(n))parts.push(p.turnaround?`Entrega indicada: **${p.turnaround}**.`:'El tiempo de entrega debe confirmarse con REPROFEM.');if(k.caveat)parts.push(`**Ten en cuenta:** ${k.caveat}`);if(p.warnings?.length)parts.push('Una indicación del documento original necesita confirmación directa con REPROFEM.');return{text:parts.join('\n\n'),products:[p],sources:sourceFor(p),suggestions:[`¿Qué preparación requiere ${p.name}?`,`¿Cuánto tarda ${p.name}?`,`¿Cuánto cuesta ${p.name}?`]}}
function compare(q){const unique=[...new Map(ranked(q).filter(x=>x.score>=6).map(x=>[x.p.id,x.p])).values()];if(unique.length<2)return null;const [a,b]=unique.slice(0,2),ka=K[String(a.code)]||{},kb=K[String(b.code)]||{};lastProductId=a.id;return{text:`**${a.name}:** ${ka.measures||'Revisa su ficha para conocer qué analiza.'}\n\n**${b.name}:** ${kb.measures||'Revisa su ficha para conocer qué analiza.'}\n\nLa diferencia principal está en lo que mide cada uno. La elección y la interpretación dependen de la indicación clínica; si tienes una orden, busca el nombre exacto que aparece en ella.`,products:[a,b],sources:[...sourceFor(a),...sourceFor(b)].filter((s,i,a)=>a.findIndex(x=>x.url===s.url)===i),suggestions:[`¿Para qué se usa ${a.name}?`,`¿Para qué se usa ${b.name}?`]}}
function reply(question,context={}){const q=String(question??'').trim(),n=norm(q);if(!q)return{text:'Escribe el nombre o código de un estudio y lo reviso contigo.',products:[],sources:[],suggestions};
if(/dolor intenso|desmayo|dificultad para respirar|sangrado abundante|emergencia|urgencia/.test(n))return{text:'Siento que estés pasando por esto. Busca atención médica urgente o llama a los servicios de emergencia de tu localidad. Este asistente no puede valorar una urgencia.',products:[],sources:[],suggestions:['Buscar un estudio por nombre']};
if(/mi resultado|mis resultados|salio (alto|bajo|positivo|negativo)|interpret|que significa.*\d/.test(n))return{text:'Puedo explicarte **qué estudia la prueba**, pero no interpretar un resultado personal. Los rangos y su significado cambian según el laboratorio, edad, antecedentes, medicamentos y otros factores. Compártelo con el profesional que lo solicitó; si me dices solo el nombre del estudio, te explico su propósito general.',products:[],sources:[],suggestions:['¿Para qué sirve la HbA1c?','Buscar por código']};
if(/sintoma|que estudio necesito|cual estudio necesito|recomiend|diagnost|tengo dolor|me duele|estoy enfer/.test(n))return{text:'Entiendo que quieras una respuesta clara. No sería seguro elegir una prueba solo a partir de síntomas: hace falta una valoración profesional. Si ya tienes una indicación u orden, puedo localizarla por nombre o código y explicarte para qué se usa, qué analiza, su precio, preparación y entrega.',products:[],sources:[],suggestions:['Buscar por código','¿Para qué sirve un estudio?','Consultar preparación']};
if(/diferencia|comparar|comparacion|versus| vs /.test(n)){const answer=compare(q);if(answer)return answer}
if(/agregalo|agregarlo|anadelo|añadelo|lo quiero/.test(n)&&getLast()){const p=getLast();return{text:`Te muestro de nuevo **${p.name}**. Pulsa **Agregar +** en la tarjeta para sumarlo a tu selección; enseguida aparecerá la barra inferior para revisarla.`,products:[p],sources:[],suggestions:['¿Cómo funciona el carrito?']}}
if(/privacidad|mis datos|guardan.*datos|inteligencia artificial/.test(n))return{text:'La conversación funciona dentro de esta página y desaparece al recargar. No se envía a REPROFEM ni a un servicio externo. Evita escribir resultados, diagnósticos u otros datos sensibles en esta vista previa.',products:[],sources:[],suggestions};
if(/hola|buenos dias|buenas tardes|ayuda|que puedes hacer/.test(n))return{text:'Hola. Puedo explicarte **para qué se usa y qué analiza cada estudio**, además de consultar precio, preparación, entrega y tu selección. También entiendo códigos, nombres incompletos y preguntas de seguimiento. La información es general y no sustituye una valoración médica.',products:[],sources:[],suggestions};
if(/carrito|seleccion|comprar|pagar|compra/.test(n)){const count=context.cart?.length||0,total=context.total;return{text:count?`Tienes **${count} ${count===1?'estudio':'estudios'}** en tu selección${total?`, con un total estimado de **${total}**`:''}. Usa **Revisar y continuar** en la barra inferior para comprobar tus datos y preparar el resumen. Esta vista previa todavía no cobra ni confirma citas.`:'Pulsa **Agregar +** en la tarjeta de un estudio. Aparecerá una barra fija en la parte inferior para revisar tu selección y continuar. Esta vista previa todavía no cobra ni confirma citas.',products:[],sources:[],suggestions:['Buscar un estudio','¿Para qué sirve la HbA1c?']};}
const clean=n.replace(/^[^a-z0-9]+/,''),queryTokens=token(q),codeIn=(String(q).match(/\b\d{3,6}\b/)||[])[0],near=products.map(p=>{const k=K[String(p.code)]||{},pt=token([p.name,...(k.aliases||[])].join(' '));return{p,d:queryTokens.filter(t=>t.length>=7).reduce((best,t)=>Math.min(best,...pt.map(h=>distance(t,h))),99)}}).filter(x=>x.d<=1).sort((a,b)=>a.d-b.d)[0],top=near?{p:near.p,score:20}:ranked(q)[0];let explicit=Boolean(near);if(top&&!explicit){const tk=K[String(top.p.code)]||{},phrases=[top.p.name,...(tk.aliases||[])].map(norm);explicit=String(top.p.code)===codeIn||phrases.some(x=>x.length>3&&n.includes(x))}if(explicit)return productAnswer(top.p,q);const follow=/^(y |entonces |ahora )?(para que|que mide|sirve|precio|cuanto|cuesta|ayuno|prepar|antes|entrega|tarda|tiempo|requisito)/.test(clean)||/^(y )?(este|ese|eso|el mismo)/.test(clean);if(follow&&getLast())return productAnswer(getLast(),q);const direct=find(q);if(direct)return productAnswer(direct,q);
if(/ayuno/.test(n)){const list=products.filter(p=>/ayuno/i.test(p.preparation||''));return{text:`Encontré **${list.length} estudios** cuya indicación menciona ayuno. La duración cambia según la prueba; abre el detalle y no modifiques medicamentos por tu cuenta.`,products:list.slice(0,3),sources:[],suggestions:['Buscar otro estudio','Consultar una preparación exacta']};}
if(/categoria|ver estudios|salud femenina|fertilidad|prenatal|solicitados|salud masculina|coprolog/.test(n)){const matched=categories.find(c=>n.includes(norm(c))),list=matched?products.filter(p=>p.category===matched):[];return{text:matched?`En **${matched}** hay ${list.length} estudios. Te muestro algunos para que revises sus detalles.`:`Puedo buscar dentro de estas áreas: **${categories.join(', ')}**. Dime el área o el nombre del estudio que necesitas.`,products:list.slice(0,3),sources:[],suggestions:['Ver salud femenina','Ver fertilidad','Buscar por código']};}
if(/cita|agenda|disponibilidad/.test(n))return{text:'La agenda aún no está conectada en esta vista previa. Puedes preparar tu selección y descargar un resumen, pero la fecha y disponibilidad deben confirmarse directamente con REPROFEM.',products:[],sources:[],suggestions:['Buscar un estudio','¿Cómo funciona el carrito?']};
const likely=ranked(q).filter(x=>x.score>=2).slice(0,3).map(x=>x.p);return{text:likely.length?'No tengo una coincidencia totalmente segura. ¿Te refieres a alguno de estos estudios?':'No encontré una coincidencia segura. Prueba con el nombre completo o el código del estudio.',products:likely,sources:[],suggestions:['Buscar por código','¿Qué estudios requieren ayuno?','¿Cómo funciona el carrito?']};}
return{reply,find};}
const api={create};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.ReprofemAssistant=api;
})(typeof window!=='undefined'?window:this);
