const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const box={module:{exports:{}}};vm.runInNewContext(fs.readFileSync('commerce.js','utf8'),box);const C=box.module.exports;
const catalogBox={window:{}};vm.runInNewContext(fs.readFileSync('catalog.js','utf8'),catalogBox);const products=catalogBox.window.REPROFEM_CATALOG.products;
const assistantBox={module:{exports:{}}};vm.runInNewContext(fs.readFileSync('chatbot.js','utf8'),assistantBox);const A=assistantBox.module.exports.create(products,{normalize:C.normalize});
test('unknown prices never become zero or a chargeable total',()=>{assert.equal(C.total([]),null);assert.equal(C.total(products.filter(p=>['2000','6025','11256'].includes(p.code))),400);assert.equal(C.total([{price:100,verified:true},{price:null,verified:false}]),null);assert.equal(C.total([{price:-1,verified:true}]),null);assert.equal(C.total([{price:0.1,verified:true},{price:0.2,verified:true}]),0.3)});
test('catalogue reconciles every provided row, code and price without legacy packages',()=>{const rows=fs.readFileSync('data/catalogo-proporcionado.tsv','utf8').trim().split(/\r?\n/).filter(x=>x.trim()).map(x=>x.split('\t').map(v=>v.trim()));const codes=new Set(rows.map(r=>r[0]));assert.equal(rows.length,47);assert.equal(codes.size,46);assert.equal(products.length,46);assert.equal(new Set(products.map(p=>p.id)).size,46);assert.equal(new Set(products.map(p=>p.category)).size,6);for(const row of rows){const p=products.find(p=>p.code===row[0]);assert.ok(p,row[0]);assert.equal(p.name,row[2]);assert.equal(p.price,Number(row[3].replace(/[$,]/g,'')));assert.equal(p.source.preparation,row[4]);assert.equal(p.source.turnaround,row[5]);assert.equal(p.verified,true);assert.equal(p.type,'estudio')}assert.equal(products.filter(p=>p.code==='4525').length,1)});
test('search handles accents, case, package contents and empty results',()=>{assert.ok(C.filter(products,'BIOmetria','Todos','all').length);assert.ok(C.filter(products,'ESTRADIOL','Todos','all').length);assert.equal(C.filter(products,'zznonexistent','Todos','all').length,0);assert.ok(C.filter(products,'','Todos','paquete').every(p=>p.type==='paquete'));assert.ok(C.filter(products,'','Fertilidad','estudio').every(p=>p.category==='Fertilidad'))});
test('minors require guardian; adults do not; empty or invalid ages are rejected',()=>{assert.ok(C.steps({age:'17'}).includes('tutor'));assert.ok(C.steps({age:'0'}).includes('tutor'));assert.ok(!C.steps({age:'18'}).includes('tutor'));for(const n of ['',-1,121,'2.5','2e1','NaN'])assert.ok(C.validate('age',n));assert.equal(C.validate('age','32'),'');assert.ok(C.validate('tutor',''))});
test('invalid dates and past dates cannot be used; blank is an explicit preference',()=>{assert.equal(C.validDate('2026-02-30','2026-01-01'),false);assert.equal(C.validDate('2026-08-30','2026-08-31'),false);assert.equal(C.validDate('2026-09-01','2026-08-31'),true);assert.equal(C.validDate('bad'),false);assert.equal(C.validate('date',''),'')});
test('required fields and email validation',()=>{for(const key of ['who','name','age','order','contact','tutor'])assert.ok(C.validate(key,''));assert.ok(C.validate('contact','invalid@'));assert.equal(C.validate('contact','prueba@example.com'),'');assert.ok(C.validate('name','<script>'));assert.equal(C.validate('name','María Ejemplo'),'')});
test('package duplicates are warned about without adding or removing products',()=>{const items=[{id:'a',name:'Paquete',includes:['Biometría hemática completa']},{id:'b',name:'Biometria hematica completa',includes:[]}];const original=JSON.stringify(items);assert.equal(C.overlaps(items).length,1);assert.equal(JSON.stringify(items),original)});
test('page anchors, source syntax and referenced local assets are complete',()=>{const html=fs.readFileSync('index.html','utf8');const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size);for(const m of html.matchAll(/href="#([^"]+)"/g))assert.ok(ids.includes(m[1]),m[1]);for(const m of html.matchAll(/(?:src|poster|href)="(assets\/[^"#]+)"/g))assert.ok(fs.existsSync(m[1]),m[1]);for(const name of ['app.js','catalog.js','commerce.js','chatbot.js'])new vm.Script(fs.readFileSync(name,'utf8'),{filename:name});assert.ok(!/localStorage|sessionStorage|fetch\(|XMLHttpRequest/.test(fs.readFileSync('app.js','utf8')))});

test('ambiguous clinical source values are preserved but not presented as confirmed instructions',()=>{for(const code of ['5153','55012','10169']){const p=products.find(p=>p.code===code);assert.equal(p.preparation,null);assert.ok(p.warnings.length);assert.ok(p.source.preparation.includes('12 a 4'))}const p=products.find(p=>p.code==='4036');assert.equal(p.turnaround,null);assert.equal(p.source.turnaround,'0 a 2');for(const p of products.filter(p=>!['5153','55012','10169'].includes(p.code)))assert.equal(p.preparation,p.source.preparation)});
test('search locates laboratory codes and all six categories',()=>{assert.equal(C.filter(products,'7254','Todos','all')[0].price,1723);assert.equal(C.filter(products,'4525','Todos','all').length,1);for(const category of new Set(products.map(p=>p.category)))assert.ok(C.filter(products,'',category,'estudio').length>0)});
test('import rejects conflicting duplicates and malformed prices',()=>{const {parseCatalog}=require('./import-catalog.cjs');const row='4525\tMAS SOLICITADOS\tInsulina\t$166\tAyuno de 8 horas\t1 dia';assert.equal(parseCatalog(row+'\n'+row).products.length,1);assert.throws(()=>parseCatalog(row+'\n'+row.replace('$166','$999')),/contradictorios/);assert.throws(()=>parseCatalog(row.replace('$166','$1,23')),/inválida/)});
test('assistant grounds product answers in the catalogue',()=>{const result=A.reply('¿Cuánto cuesta la progesterona?');assert.match(result.text,/precio/i);assert.equal(result.products[0].name,'Progesterona');assert.equal(A.reply('información del código 7254').products[0].code,'7254')});
test('assistant protects ambiguous preparation and medical boundaries',()=>{assert.match(A.reply('¿Qué preparación tiene el código 5153?').text,/pendiente de aclaración|confirm/i);const symptoms=A.reply('Tengo dolor, ¿qué estudio necesito?');assert.match(symptoms.text,/valoración profesional/i);assert.doesNotMatch(symptoms.text,/debes hacerte|te recomiendo el estudio/i)});
test('assistant recognizes emergencies, privacy and cart context',()=>{assert.match(A.reply('Tengo sangrado abundante y me desmayé').text,/atención médica urgente/i);assert.match(A.reply('¿Guardan mis datos?').text,/no se envía/i);assert.match(A.reply('¿Cómo funciona el carrito?',{cart:[products[0]],total:'$100 MXN'}).text,/1 estudio/)});
